#pragma once

// Display pin definitions for ESP32S3-ZERO with ST7789

#define ESP32S3_ZERO_LCD_SPI_HOST SPI3_HOST
#define ESP32S3_ZERO_LCD_PIN_MISO GPIO_NUM_13
#define ESP32S3_ZERO_LCD_PIN_MOSI GPIO_NUM_11
#define ESP32S3_ZERO_LCD_PIN_CLOCK GPIO_NUM_12
#define ESP32S3_ZERO_LCD_PIN_RESET GPIO_NUM_46
#define ESP32S3_ZERO_LCD_PIN_DC GPIO_NUM_14
#define ESP32S3_ZERO_LCD_PIN_CS GPIO_NUM_10

#define ESP32S3_ZERO_LCD_PIN_BACKLIGHT GPIO_NUM_3

// Display resolution
#define ESP32S3_ZERO_LCD_HORIZONTAL_RESOLUTION 320 //revert
#define ESP32S3_ZERO_LCD_VERTICAL_RESOLUTION 240 //revert


// SD Card pin definitions (software SPI)
#define ESP32S3_ZERO_SD_PIN_CS GPIO_NUM_39
#define ESP32S3_ZERO_SD_PIN_MOSI GPIO_NUM_41
#define ESP32S3_ZERO_SD_PIN_MISO GPIO_NUM_38
#define ESP32S3_ZERO_SD_PIN_CLOCK GPIO_NUM_40

// I2C pins for PCA9555 IO expander (buttons)
#define ESP32S3_ZERO_I2C_SDA GPIO_NUM_8
#define ESP32S3_ZERO_I2C_SCL GPIO_NUM_9

// Built-in LED
#define ESP32S3_ZERO_LED_PIN GPIO_NUM_2

// Additional features
#define ESP32S3_ZERO_VIBRATION_PIN GPIO_NUM_1
#define ESP32S3_ZERO_IR_RECEIVE_PIN GPIO_NUM_35
#define ESP32S3_ZERO_IR_TRANSMIT_PIN GPIO_NUM_1 // Same as vibration

// NRF24L01 radio pins (uses same SPI as display)
#define ESP32S3_ZERO_NRF_CSN_PIN GPIO_NUM_45
#define ESP32S3_ZERO_NRF_CE_PIN GPIO_NUM_48
